#ifndef _QISHGEN_TIMESTAMP
/*** file _qishgen.h generated by genqish.c ** DO NOT EDIT **/
#define _QISHGEN_TIMESTAMP "Sat Aug 20 11:37:58 2011"
#define QISH_SETJMP_SIZE 148 /*sizeof(jmp_buf) in bytes*/
#define QISH_PAGESIZE 4096
/* ARGMAX=262144 */
/* STREAM_MAX=256 */
#define QISH_OPEN_MAX 256
#define QISH_SRCDIR "/Users/jtregunna/Projects/acute/bootstrap/c/Qish_1.0pre1/lib"
/* CHILD_MAX=709 */
/* CLK_TCK=100 */
/* host: lore.local */
#define QISH_POINTER_SIZE 8
/* sizeof int:4 long:8 long long:8 double:8 ptr:8 funptr:8 wchar_t:4 */
typedef unsigned long qish_uaddr_t; /*8bytes, same as void* */
typedef qish_uaddr_t qish_uword_t;

typedef long qish_word_t; /*8bytes, same as void* */

/*pa=0x7fff65bba55c &b=0x7fff65bba534 &c=0x7fff65bba530 &delta=0x7fff65bba52c delta=-10*/
#define QISH_STACK_DOWN 1 
#define QISH_STACK_UP 0

#define QISH_ARGS_DOWN 1
#define QISH_ARGS_UP 0

#endif /*_QISHGEN_TIMESTAMP*/
