#! /usr/bin/env ruby
# -*- ruby -*- 
# emacs Time-stamp: <Apr 16 2002 16:08:01 Basile STARYNKEVITCH hector.lesours>
# prcsid $Id: gen_locals 25 2005-07-08 08:54:46Z basile $
def process(inputfile, outputfile) 
  htb = { }
  IO.foreach(inputfile) do |line|
    line.gsub(/\bl_[a-z0-9_]+\b/) do |nam|
      htb[nam] = nam[2 .. 99]
    end
  end
  arrnam = [ ]
  htb.each { |k,n| arrnam << n }
  arrnam.sort!
  File.rename(outputfile, outputfile+"~") if FileTest.exists?(outputfile)
  open (outputfile, "w") do |outf|
    outf.printf("/* file %s generated at %s from %s */\n", outputfile, Time.now, inputfile);
    outf.printf("/* DON'T EDIT */\n")
    arrnam.each { |nam| outf.printf("#define l_%s _locals_.%s\n",nam,nam) }
    outf.printf("/* eof %s */\n", outputfile)
  end
end

inputfile= $*[0]
outputfile= $*[1]
process(inputfile, outputfile)	
# eof $Id: gen_locals 25 2005-07-08 08:54:46Z basile $

